//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.EstudioJuridico
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Estudio_JuridicoEntities : DbContext
    {
        public Estudio_JuridicoEntities()
            : base("name=Estudio_JuridicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spFichaPredialPropietariosconsultar_Result> spFichaPredialPropietariosconsultar(Nullable<int> id_ficha, Nullable<int> id_propietario, string anotacion, Nullable<int> id_ficha_predial_propietario)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            var id_propietarioParameter = id_propietario.HasValue ?
                new ObjectParameter("id_propietario", id_propietario) :
                new ObjectParameter("id_propietario", typeof(int));
    
            var anotacionParameter = anotacion != null ?
                new ObjectParameter("anotacion", anotacion) :
                new ObjectParameter("anotacion", typeof(string));
    
            var id_ficha_predial_propietarioParameter = id_ficha_predial_propietario.HasValue ?
                new ObjectParameter("id_ficha_predial_propietario", id_ficha_predial_propietario) :
                new ObjectParameter("id_ficha_predial_propietario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFichaPredialPropietariosconsultar_Result>("spFichaPredialPropietariosconsultar", id_fichaParameter, id_propietarioParameter, anotacionParameter, id_ficha_predial_propietarioParameter);
        }
    
        public virtual int spFichaPredialPropietarioscrear(Nullable<int> id_ficha, Nullable<int> id_propietario, string anotacion)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            var id_propietarioParameter = id_propietario.HasValue ?
                new ObjectParameter("id_propietario", id_propietario) :
                new ObjectParameter("id_propietario", typeof(int));
    
            var anotacionParameter = anotacion != null ?
                new ObjectParameter("anotacion", anotacion) :
                new ObjectParameter("anotacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFichaPredialPropietarioscrear", id_fichaParameter, id_propietarioParameter, anotacionParameter);
        }
    
        public virtual int spFichaPredialPropietariosmodificar(Nullable<int> id_ficha_perdial_propietario, Nullable<int> id_propietario, string anotacion)
        {
            var id_ficha_perdial_propietarioParameter = id_ficha_perdial_propietario.HasValue ?
                new ObjectParameter("id_ficha_perdial_propietario", id_ficha_perdial_propietario) :
                new ObjectParameter("id_ficha_perdial_propietario", typeof(int));
    
            var id_propietarioParameter = id_propietario.HasValue ?
                new ObjectParameter("id_propietario", id_propietario) :
                new ObjectParameter("id_propietario", typeof(int));
    
            var anotacionParameter = anotacion != null ?
                new ObjectParameter("anotacion", anotacion) :
                new ObjectParameter("anotacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFichaPredialPropietariosmodificar", id_ficha_perdial_propietarioParameter, id_propietarioParameter, anotacionParameter);
        }
    
        public virtual ObjectResult<spMatriculaDerivadasconsultar_Result> spMatriculaDerivadasconsultar(Nullable<int> id_ficha, string matricula, Nullable<bool> estado, string pk_predio, string ubicar)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("matricula", matricula) :
                new ObjectParameter("matricula", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var pk_predioParameter = pk_predio != null ?
                new ObjectParameter("pk_predio", pk_predio) :
                new ObjectParameter("pk_predio", typeof(string));
    
            var ubicarParameter = ubicar != null ?
                new ObjectParameter("ubicar", ubicar) :
                new ObjectParameter("ubicar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMatriculaDerivadasconsultar_Result>("spMatriculaDerivadasconsultar", id_fichaParameter, matriculaParameter, estadoParameter, pk_predioParameter, ubicarParameter);
        }
    
        public virtual int spMatriculaDerivadascrear(Nullable<int> id_ficha, string matricula, Nullable<bool> estado, string pk_predio, string ubicar)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("matricula", matricula) :
                new ObjectParameter("matricula", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var pk_predioParameter = pk_predio != null ?
                new ObjectParameter("pk_predio", pk_predio) :
                new ObjectParameter("pk_predio", typeof(string));
    
            var ubicarParameter = ubicar != null ?
                new ObjectParameter("ubicar", ubicar) :
                new ObjectParameter("ubicar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spMatriculaDerivadascrear", id_fichaParameter, matriculaParameter, estadoParameter, pk_predioParameter, ubicarParameter);
        }
    
        public virtual int spMatriculaDerivadaseliminar(Nullable<int> id_ficha)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spMatriculaDerivadaseliminar", id_fichaParameter);
        }
    
        public virtual int spMatriculaDerivadasmodificar(Nullable<int> id_matricula_derivada, string matricula, Nullable<bool> estado, string pk_predio, string ubicar)
        {
            var id_matricula_derivadaParameter = id_matricula_derivada.HasValue ?
                new ObjectParameter("id_matricula_derivada", id_matricula_derivada) :
                new ObjectParameter("id_matricula_derivada", typeof(int));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("matricula", matricula) :
                new ObjectParameter("matricula", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var pk_predioParameter = pk_predio != null ?
                new ObjectParameter("pk_predio", pk_predio) :
                new ObjectParameter("pk_predio", typeof(string));
    
            var ubicarParameter = ubicar != null ?
                new ObjectParameter("ubicar", ubicar) :
                new ObjectParameter("ubicar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spMatriculaDerivadasmodificar", id_matricula_derivadaParameter, matriculaParameter, estadoParameter, pk_predioParameter, ubicarParameter);
        }
    
        public virtual int spFichaPredialHistoriaPropietarioseliminar(Nullable<int> id_ficha)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFichaPredialHistoriaPropietarioseliminar", id_fichaParameter);
        }
    
        public virtual ObjectResult<spFichaPredialeHistoriaPropietariosconsultar_Result> spFichaPredialeHistoriaPropietariosconsultar(Nullable<int> id_ficha)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFichaPredialeHistoriaPropietariosconsultar_Result>("spFichaPredialeHistoriaPropietariosconsultar", id_fichaParameter);
        }
    
        public virtual int spFichaPredialeHistoriaPropietarioscrear(string causa_acto, string propietario, string titulo, string notaria, Nullable<System.DateTime> fecha_escritura, Nullable<System.DateTime> fecha_registro, Nullable<decimal> area, string vendedor_anterior, Nullable<int> id_ficha, string anotacion)
        {
            var causa_actoParameter = causa_acto != null ?
                new ObjectParameter("causa_acto", causa_acto) :
                new ObjectParameter("causa_acto", typeof(string));
    
            var propietarioParameter = propietario != null ?
                new ObjectParameter("propietario", propietario) :
                new ObjectParameter("propietario", typeof(string));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var notariaParameter = notaria != null ?
                new ObjectParameter("notaria", notaria) :
                new ObjectParameter("notaria", typeof(string));
    
            var fecha_escrituraParameter = fecha_escritura.HasValue ?
                new ObjectParameter("fecha_escritura", fecha_escritura) :
                new ObjectParameter("fecha_escritura", typeof(System.DateTime));
    
            var fecha_registroParameter = fecha_registro.HasValue ?
                new ObjectParameter("fecha_registro", fecha_registro) :
                new ObjectParameter("fecha_registro", typeof(System.DateTime));
    
            var areaParameter = area.HasValue ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(decimal));
    
            var vendedor_anteriorParameter = vendedor_anterior != null ?
                new ObjectParameter("vendedor_anterior", vendedor_anterior) :
                new ObjectParameter("vendedor_anterior", typeof(string));
    
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            var anotacionParameter = anotacion != null ?
                new ObjectParameter("anotacion", anotacion) :
                new ObjectParameter("anotacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFichaPredialeHistoriaPropietarioscrear", causa_actoParameter, propietarioParameter, tituloParameter, notariaParameter, fecha_escrituraParameter, fecha_registroParameter, areaParameter, vendedor_anteriorParameter, id_fichaParameter, anotacionParameter);
        }
    
        public virtual int spFichaPredialeHistoriaPropietariosmodificar(Nullable<int> id_historiapropietarios, string causa_acto, string propietario, string titulo, string notaria, Nullable<System.DateTime> fecha_escritura, Nullable<System.DateTime> fecha_registro, Nullable<decimal> area, string vendedor_anterior, Nullable<int> id_ficha, string anotacion)
        {
            var id_historiapropietariosParameter = id_historiapropietarios.HasValue ?
                new ObjectParameter("id_historiapropietarios", id_historiapropietarios) :
                new ObjectParameter("id_historiapropietarios", typeof(int));
    
            var causa_actoParameter = causa_acto != null ?
                new ObjectParameter("causa_acto", causa_acto) :
                new ObjectParameter("causa_acto", typeof(string));
    
            var propietarioParameter = propietario != null ?
                new ObjectParameter("propietario", propietario) :
                new ObjectParameter("propietario", typeof(string));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var notariaParameter = notaria != null ?
                new ObjectParameter("notaria", notaria) :
                new ObjectParameter("notaria", typeof(string));
    
            var fecha_escrituraParameter = fecha_escritura.HasValue ?
                new ObjectParameter("fecha_escritura", fecha_escritura) :
                new ObjectParameter("fecha_escritura", typeof(System.DateTime));
    
            var fecha_registroParameter = fecha_registro.HasValue ?
                new ObjectParameter("fecha_registro", fecha_registro) :
                new ObjectParameter("fecha_registro", typeof(System.DateTime));
    
            var areaParameter = area.HasValue ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(decimal));
    
            var vendedor_anteriorParameter = vendedor_anterior != null ?
                new ObjectParameter("vendedor_anterior", vendedor_anterior) :
                new ObjectParameter("vendedor_anterior", typeof(string));
    
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            var anotacionParameter = anotacion != null ?
                new ObjectParameter("anotacion", anotacion) :
                new ObjectParameter("anotacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFichaPredialeHistoriaPropietariosmodificar", id_historiapropietariosParameter, causa_actoParameter, propietarioParameter, tituloParameter, notariaParameter, fecha_escrituraParameter, fecha_registroParameter, areaParameter, vendedor_anteriorParameter, id_fichaParameter, anotacionParameter);
        }
    
        public virtual ObjectResult<spFichaPredialesconsultar_Result> spFichaPredialesconsultar(string numero_ficha)
        {
            var numero_fichaParameter = numero_ficha != null ?
                new ObjectParameter("numero_ficha", numero_ficha) :
                new ObjectParameter("numero_ficha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFichaPredialesconsultar_Result>("spFichaPredialesconsultar", numero_fichaParameter);
        }
    
        public virtual int spFichaPredialescrear(string numero_ficha, string folio_matriz, Nullable<bool> estado_folio_matriz, Nullable<System.DateTime> fecha_apertura_folio, Nullable<System.DateTime> fecha_primera_anotacion, Nullable<decimal> area_escritura, Nullable<decimal> area_ovc, Nullable<decimal> area_folio, string ruta_archivo, string razon_diferencia_areas, string antecedentes, string estudio_folio_matriz, string analisis_areas, string anotacion_que_afecta_la_inscripcion, string proteccion_colectiva, string linderos, string instrucciones_visita_campo, string direccion_folio, string quien_elaboro_yaprobo, Nullable<System.DateTime> fecha_control_calidad_juridico, string control_calidad_juridico, string aprobacion_interventoria, Nullable<System.DateTime> fecha_aprobacion, string linderos_escritura, string linderos_folio, string linderos_campo, string analisis_de_hecho_y_derecho, Nullable<bool> inscripcion_catastro, Nullable<bool> antecedentes_registrales, string concepto_juridico, string recomendaciones, string documentos_analizados, string lindero_norte, string lindero_occidente, string lindero_oriente, string lindero_sur, string pk_predio_folio_matriz, string direccion_ovc, Nullable<bool> enla_escritura_se_relaciona_plano_protocolizado, string complementacion, string observaciones_con_respeto_al_propietario, Nullable<bool> se_diligencio_ficha_predial, Nullable<bool> la_visita_de_campo_produjo_informe, Nullable<bool> se_levanto_acta_de_colindacia, string situacion_juridica_inmueble, string numero_carpeta, string tarjeta_profesional_juridico, string coordinador_juridico, string nombre_interventor, string codigo_municipio, string descripcion_municipio, string datos_informe_juridico, string datos_informe_campo, string descripicion_destino, string descripicion_sector, string descripicion_adquisicion, string numero_ficha_ovc)
        {
            var numero_fichaParameter = numero_ficha != null ?
                new ObjectParameter("numero_ficha", numero_ficha) :
                new ObjectParameter("numero_ficha", typeof(string));
    
            var folio_matrizParameter = folio_matriz != null ?
                new ObjectParameter("folio_matriz", folio_matriz) :
                new ObjectParameter("folio_matriz", typeof(string));
    
            var estado_folio_matrizParameter = estado_folio_matriz.HasValue ?
                new ObjectParameter("estado_folio_matriz", estado_folio_matriz) :
                new ObjectParameter("estado_folio_matriz", typeof(bool));
    
            var fecha_apertura_folioParameter = fecha_apertura_folio.HasValue ?
                new ObjectParameter("fecha_apertura_folio", fecha_apertura_folio) :
                new ObjectParameter("fecha_apertura_folio", typeof(System.DateTime));
    
            var fecha_primera_anotacionParameter = fecha_primera_anotacion.HasValue ?
                new ObjectParameter("fecha_primera_anotacion", fecha_primera_anotacion) :
                new ObjectParameter("fecha_primera_anotacion", typeof(System.DateTime));
    
            var area_escrituraParameter = area_escritura.HasValue ?
                new ObjectParameter("area_escritura", area_escritura) :
                new ObjectParameter("area_escritura", typeof(decimal));
    
            var area_ovcParameter = area_ovc.HasValue ?
                new ObjectParameter("area_ovc", area_ovc) :
                new ObjectParameter("area_ovc", typeof(decimal));
    
            var area_folioParameter = area_folio.HasValue ?
                new ObjectParameter("area_folio", area_folio) :
                new ObjectParameter("area_folio", typeof(decimal));
    
            var ruta_archivoParameter = ruta_archivo != null ?
                new ObjectParameter("ruta_archivo", ruta_archivo) :
                new ObjectParameter("ruta_archivo", typeof(string));
    
            var razon_diferencia_areasParameter = razon_diferencia_areas != null ?
                new ObjectParameter("razon_diferencia_areas", razon_diferencia_areas) :
                new ObjectParameter("razon_diferencia_areas", typeof(string));
    
            var antecedentesParameter = antecedentes != null ?
                new ObjectParameter("antecedentes", antecedentes) :
                new ObjectParameter("antecedentes", typeof(string));
    
            var estudio_folio_matrizParameter = estudio_folio_matriz != null ?
                new ObjectParameter("estudio_folio_matriz", estudio_folio_matriz) :
                new ObjectParameter("estudio_folio_matriz", typeof(string));
    
            var analisis_areasParameter = analisis_areas != null ?
                new ObjectParameter("analisis_areas", analisis_areas) :
                new ObjectParameter("analisis_areas", typeof(string));
    
            var anotacion_que_afecta_la_inscripcionParameter = anotacion_que_afecta_la_inscripcion != null ?
                new ObjectParameter("anotacion_que_afecta_la_inscripcion", anotacion_que_afecta_la_inscripcion) :
                new ObjectParameter("anotacion_que_afecta_la_inscripcion", typeof(string));
    
            var proteccion_colectivaParameter = proteccion_colectiva != null ?
                new ObjectParameter("proteccion_colectiva", proteccion_colectiva) :
                new ObjectParameter("proteccion_colectiva", typeof(string));
    
            var linderosParameter = linderos != null ?
                new ObjectParameter("linderos", linderos) :
                new ObjectParameter("linderos", typeof(string));
    
            var instrucciones_visita_campoParameter = instrucciones_visita_campo != null ?
                new ObjectParameter("instrucciones_visita_campo", instrucciones_visita_campo) :
                new ObjectParameter("instrucciones_visita_campo", typeof(string));
    
            var direccion_folioParameter = direccion_folio != null ?
                new ObjectParameter("direccion_folio", direccion_folio) :
                new ObjectParameter("direccion_folio", typeof(string));
    
            var quien_elaboro_yaproboParameter = quien_elaboro_yaprobo != null ?
                new ObjectParameter("quien_elaboro_yaprobo", quien_elaboro_yaprobo) :
                new ObjectParameter("quien_elaboro_yaprobo", typeof(string));
    
            var fecha_control_calidad_juridicoParameter = fecha_control_calidad_juridico.HasValue ?
                new ObjectParameter("fecha_control_calidad_juridico", fecha_control_calidad_juridico) :
                new ObjectParameter("fecha_control_calidad_juridico", typeof(System.DateTime));
    
            var control_calidad_juridicoParameter = control_calidad_juridico != null ?
                new ObjectParameter("control_calidad_juridico", control_calidad_juridico) :
                new ObjectParameter("control_calidad_juridico", typeof(string));
    
            var aprobacion_interventoriaParameter = aprobacion_interventoria != null ?
                new ObjectParameter("aprobacion_interventoria", aprobacion_interventoria) :
                new ObjectParameter("aprobacion_interventoria", typeof(string));
    
            var fecha_aprobacionParameter = fecha_aprobacion.HasValue ?
                new ObjectParameter("fecha_aprobacion", fecha_aprobacion) :
                new ObjectParameter("fecha_aprobacion", typeof(System.DateTime));
    
            var linderos_escrituraParameter = linderos_escritura != null ?
                new ObjectParameter("linderos_escritura", linderos_escritura) :
                new ObjectParameter("linderos_escritura", typeof(string));
    
            var linderos_folioParameter = linderos_folio != null ?
                new ObjectParameter("linderos_folio", linderos_folio) :
                new ObjectParameter("linderos_folio", typeof(string));
    
            var linderos_campoParameter = linderos_campo != null ?
                new ObjectParameter("linderos_campo", linderos_campo) :
                new ObjectParameter("linderos_campo", typeof(string));
    
            var analisis_de_hecho_y_derechoParameter = analisis_de_hecho_y_derecho != null ?
                new ObjectParameter("analisis_de_hecho_y_derecho", analisis_de_hecho_y_derecho) :
                new ObjectParameter("analisis_de_hecho_y_derecho", typeof(string));
    
            var inscripcion_catastroParameter = inscripcion_catastro.HasValue ?
                new ObjectParameter("inscripcion_catastro", inscripcion_catastro) :
                new ObjectParameter("inscripcion_catastro", typeof(bool));
    
            var antecedentes_registralesParameter = antecedentes_registrales.HasValue ?
                new ObjectParameter("antecedentes_registrales", antecedentes_registrales) :
                new ObjectParameter("antecedentes_registrales", typeof(bool));
    
            var concepto_juridicoParameter = concepto_juridico != null ?
                new ObjectParameter("concepto_juridico", concepto_juridico) :
                new ObjectParameter("concepto_juridico", typeof(string));
    
            var recomendacionesParameter = recomendaciones != null ?
                new ObjectParameter("recomendaciones", recomendaciones) :
                new ObjectParameter("recomendaciones", typeof(string));
    
            var documentos_analizadosParameter = documentos_analizados != null ?
                new ObjectParameter("documentos_analizados", documentos_analizados) :
                new ObjectParameter("documentos_analizados", typeof(string));
    
            var lindero_norteParameter = lindero_norte != null ?
                new ObjectParameter("lindero_norte", lindero_norte) :
                new ObjectParameter("lindero_norte", typeof(string));
    
            var lindero_occidenteParameter = lindero_occidente != null ?
                new ObjectParameter("lindero_occidente", lindero_occidente) :
                new ObjectParameter("lindero_occidente", typeof(string));
    
            var lindero_orienteParameter = lindero_oriente != null ?
                new ObjectParameter("lindero_oriente", lindero_oriente) :
                new ObjectParameter("lindero_oriente", typeof(string));
    
            var lindero_surParameter = lindero_sur != null ?
                new ObjectParameter("lindero_sur", lindero_sur) :
                new ObjectParameter("lindero_sur", typeof(string));
    
            var pk_predio_folio_matrizParameter = pk_predio_folio_matriz != null ?
                new ObjectParameter("pk_predio_folio_matriz", pk_predio_folio_matriz) :
                new ObjectParameter("pk_predio_folio_matriz", typeof(string));
    
            var direccion_ovcParameter = direccion_ovc != null ?
                new ObjectParameter("direccion_ovc", direccion_ovc) :
                new ObjectParameter("direccion_ovc", typeof(string));
    
            var enla_escritura_se_relaciona_plano_protocolizadoParameter = enla_escritura_se_relaciona_plano_protocolizado.HasValue ?
                new ObjectParameter("enla_escritura_se_relaciona_plano_protocolizado", enla_escritura_se_relaciona_plano_protocolizado) :
                new ObjectParameter("enla_escritura_se_relaciona_plano_protocolizado", typeof(bool));
    
            var complementacionParameter = complementacion != null ?
                new ObjectParameter("complementacion", complementacion) :
                new ObjectParameter("complementacion", typeof(string));
    
            var observaciones_con_respeto_al_propietarioParameter = observaciones_con_respeto_al_propietario != null ?
                new ObjectParameter("observaciones_con_respeto_al_propietario", observaciones_con_respeto_al_propietario) :
                new ObjectParameter("observaciones_con_respeto_al_propietario", typeof(string));
    
            var se_diligencio_ficha_predialParameter = se_diligencio_ficha_predial.HasValue ?
                new ObjectParameter("se_diligencio_ficha_predial", se_diligencio_ficha_predial) :
                new ObjectParameter("se_diligencio_ficha_predial", typeof(bool));
    
            var la_visita_de_campo_produjo_informeParameter = la_visita_de_campo_produjo_informe.HasValue ?
                new ObjectParameter("la_visita_de_campo_produjo_informe", la_visita_de_campo_produjo_informe) :
                new ObjectParameter("la_visita_de_campo_produjo_informe", typeof(bool));
    
            var se_levanto_acta_de_colindaciaParameter = se_levanto_acta_de_colindacia.HasValue ?
                new ObjectParameter("se_levanto_acta_de_colindacia", se_levanto_acta_de_colindacia) :
                new ObjectParameter("se_levanto_acta_de_colindacia", typeof(bool));
    
            var situacion_juridica_inmuebleParameter = situacion_juridica_inmueble != null ?
                new ObjectParameter("situacion_juridica_inmueble", situacion_juridica_inmueble) :
                new ObjectParameter("situacion_juridica_inmueble", typeof(string));
    
            var numero_carpetaParameter = numero_carpeta != null ?
                new ObjectParameter("numero_carpeta", numero_carpeta) :
                new ObjectParameter("numero_carpeta", typeof(string));
    
            var tarjeta_profesional_juridicoParameter = tarjeta_profesional_juridico != null ?
                new ObjectParameter("tarjeta_profesional_juridico", tarjeta_profesional_juridico) :
                new ObjectParameter("tarjeta_profesional_juridico", typeof(string));
    
            var coordinador_juridicoParameter = coordinador_juridico != null ?
                new ObjectParameter("coordinador_juridico", coordinador_juridico) :
                new ObjectParameter("coordinador_juridico", typeof(string));
    
            var nombre_interventorParameter = nombre_interventor != null ?
                new ObjectParameter("nombre_interventor", nombre_interventor) :
                new ObjectParameter("nombre_interventor", typeof(string));
    
            var codigo_municipioParameter = codigo_municipio != null ?
                new ObjectParameter("codigo_municipio", codigo_municipio) :
                new ObjectParameter("codigo_municipio", typeof(string));
    
            var descripcion_municipioParameter = descripcion_municipio != null ?
                new ObjectParameter("descripcion_municipio", descripcion_municipio) :
                new ObjectParameter("descripcion_municipio", typeof(string));
    
            var datos_informe_juridicoParameter = datos_informe_juridico != null ?
                new ObjectParameter("datos_informe_juridico", datos_informe_juridico) :
                new ObjectParameter("datos_informe_juridico", typeof(string));
    
            var datos_informe_campoParameter = datos_informe_campo != null ?
                new ObjectParameter("datos_informe_campo", datos_informe_campo) :
                new ObjectParameter("datos_informe_campo", typeof(string));
    
            var descripicion_destinoParameter = descripicion_destino != null ?
                new ObjectParameter("descripicion_destino", descripicion_destino) :
                new ObjectParameter("descripicion_destino", typeof(string));
    
            var descripicion_sectorParameter = descripicion_sector != null ?
                new ObjectParameter("descripicion_sector", descripicion_sector) :
                new ObjectParameter("descripicion_sector", typeof(string));
    
            var descripicion_adquisicionParameter = descripicion_adquisicion != null ?
                new ObjectParameter("descripicion_adquisicion", descripicion_adquisicion) :
                new ObjectParameter("descripicion_adquisicion", typeof(string));
    
            var numero_ficha_ovcParameter = numero_ficha_ovc != null ?
                new ObjectParameter("numero_ficha_ovc", numero_ficha_ovc) :
                new ObjectParameter("numero_ficha_ovc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFichaPredialescrear", numero_fichaParameter, folio_matrizParameter, estado_folio_matrizParameter, fecha_apertura_folioParameter, fecha_primera_anotacionParameter, area_escrituraParameter, area_ovcParameter, area_folioParameter, ruta_archivoParameter, razon_diferencia_areasParameter, antecedentesParameter, estudio_folio_matrizParameter, analisis_areasParameter, anotacion_que_afecta_la_inscripcionParameter, proteccion_colectivaParameter, linderosParameter, instrucciones_visita_campoParameter, direccion_folioParameter, quien_elaboro_yaproboParameter, fecha_control_calidad_juridicoParameter, control_calidad_juridicoParameter, aprobacion_interventoriaParameter, fecha_aprobacionParameter, linderos_escrituraParameter, linderos_folioParameter, linderos_campoParameter, analisis_de_hecho_y_derechoParameter, inscripcion_catastroParameter, antecedentes_registralesParameter, concepto_juridicoParameter, recomendacionesParameter, documentos_analizadosParameter, lindero_norteParameter, lindero_occidenteParameter, lindero_orienteParameter, lindero_surParameter, pk_predio_folio_matrizParameter, direccion_ovcParameter, enla_escritura_se_relaciona_plano_protocolizadoParameter, complementacionParameter, observaciones_con_respeto_al_propietarioParameter, se_diligencio_ficha_predialParameter, la_visita_de_campo_produjo_informeParameter, se_levanto_acta_de_colindaciaParameter, situacion_juridica_inmuebleParameter, numero_carpetaParameter, tarjeta_profesional_juridicoParameter, coordinador_juridicoParameter, nombre_interventorParameter, codigo_municipioParameter, descripcion_municipioParameter, datos_informe_juridicoParameter, datos_informe_campoParameter, descripicion_destinoParameter, descripicion_sectorParameter, descripicion_adquisicionParameter, numero_ficha_ovcParameter);
        }
    
        public virtual int spFichaPredialeseliminar(Nullable<int> id_ficha)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFichaPredialeseliminar", id_fichaParameter);
        }
    
        public virtual int spFichaPredialesmodificar(Nullable<int> id_ficha, string folio_matriz, Nullable<bool> estado_folio_matriz, Nullable<System.DateTime> fecha_apertura_folio, Nullable<System.DateTime> fecha_primera_anotacion, Nullable<decimal> area_escritura, Nullable<decimal> area_ovc, Nullable<decimal> area_folio, string ruta_archivo, string razon_diferencia_areas, string antecedentes, string estudio_folio_matriz, string analisis_areas, string anotacion_que_afecta_la_inscripcion, string proteccion_colectiva, string linderos, string instrucciones_visita_campo, string direccion_folio, string quien_elaboro_yaprobo, Nullable<System.DateTime> fecha_control_calidad_juridico, string control_calidad_juridico, string aprobacion_interventoria, Nullable<System.DateTime> fecha_aprobacion, string linderos_escritura, string linderos_folio, string linderos_campo, string analisis_de_hecho_y_derecho, Nullable<bool> inscripcion_catastro, Nullable<bool> antecedentes_registrales, string concepto_juridico, string recomendaciones, string documentos_analizados, string lindero_norte, string lindero_occidente, string lindero_oriente, string lindero_sur, string pk_predio_folio_matriz, string direccion_ovc, Nullable<bool> enla_escritura_se_relaciona_plano_protocolizado, string complementacion, string observaciones_con_respeto_al_propietario, Nullable<bool> se_diligencio_ficha_predial, Nullable<bool> la_visita_de_campo_produjo_informe, Nullable<bool> se_levanto_acta_de_colindacia, string situacion_juridica_inmueble, string numero_carpeta, string tarjeta_profesional_juridico, string coordinador_juridico, string nombre_interventor, string codigo_municipio, string descripcion_municipio, string datos_informe_juridico, string datos_informe_campo, string descripicion_destino, string descripicion_sector, string descripicion_adquisicion, string numero_ficha_ovc)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            var folio_matrizParameter = folio_matriz != null ?
                new ObjectParameter("folio_matriz", folio_matriz) :
                new ObjectParameter("folio_matriz", typeof(string));
    
            var estado_folio_matrizParameter = estado_folio_matriz.HasValue ?
                new ObjectParameter("estado_folio_matriz", estado_folio_matriz) :
                new ObjectParameter("estado_folio_matriz", typeof(bool));
    
            var fecha_apertura_folioParameter = fecha_apertura_folio.HasValue ?
                new ObjectParameter("fecha_apertura_folio", fecha_apertura_folio) :
                new ObjectParameter("fecha_apertura_folio", typeof(System.DateTime));
    
            var fecha_primera_anotacionParameter = fecha_primera_anotacion.HasValue ?
                new ObjectParameter("fecha_primera_anotacion", fecha_primera_anotacion) :
                new ObjectParameter("fecha_primera_anotacion", typeof(System.DateTime));
    
            var area_escrituraParameter = area_escritura.HasValue ?
                new ObjectParameter("area_escritura", area_escritura) :
                new ObjectParameter("area_escritura", typeof(decimal));
    
            var area_ovcParameter = area_ovc.HasValue ?
                new ObjectParameter("area_ovc", area_ovc) :
                new ObjectParameter("area_ovc", typeof(decimal));
    
            var area_folioParameter = area_folio.HasValue ?
                new ObjectParameter("area_folio", area_folio) :
                new ObjectParameter("area_folio", typeof(decimal));
    
            var ruta_archivoParameter = ruta_archivo != null ?
                new ObjectParameter("ruta_archivo", ruta_archivo) :
                new ObjectParameter("ruta_archivo", typeof(string));
    
            var razon_diferencia_areasParameter = razon_diferencia_areas != null ?
                new ObjectParameter("razon_diferencia_areas", razon_diferencia_areas) :
                new ObjectParameter("razon_diferencia_areas", typeof(string));
    
            var antecedentesParameter = antecedentes != null ?
                new ObjectParameter("antecedentes", antecedentes) :
                new ObjectParameter("antecedentes", typeof(string));
    
            var estudio_folio_matrizParameter = estudio_folio_matriz != null ?
                new ObjectParameter("estudio_folio_matriz", estudio_folio_matriz) :
                new ObjectParameter("estudio_folio_matriz", typeof(string));
    
            var analisis_areasParameter = analisis_areas != null ?
                new ObjectParameter("analisis_areas", analisis_areas) :
                new ObjectParameter("analisis_areas", typeof(string));
    
            var anotacion_que_afecta_la_inscripcionParameter = anotacion_que_afecta_la_inscripcion != null ?
                new ObjectParameter("anotacion_que_afecta_la_inscripcion", anotacion_que_afecta_la_inscripcion) :
                new ObjectParameter("anotacion_que_afecta_la_inscripcion", typeof(string));
    
            var proteccion_colectivaParameter = proteccion_colectiva != null ?
                new ObjectParameter("proteccion_colectiva", proteccion_colectiva) :
                new ObjectParameter("proteccion_colectiva", typeof(string));
    
            var linderosParameter = linderos != null ?
                new ObjectParameter("linderos", linderos) :
                new ObjectParameter("linderos", typeof(string));
    
            var instrucciones_visita_campoParameter = instrucciones_visita_campo != null ?
                new ObjectParameter("instrucciones_visita_campo", instrucciones_visita_campo) :
                new ObjectParameter("instrucciones_visita_campo", typeof(string));
    
            var direccion_folioParameter = direccion_folio != null ?
                new ObjectParameter("direccion_folio", direccion_folio) :
                new ObjectParameter("direccion_folio", typeof(string));
    
            var quien_elaboro_yaproboParameter = quien_elaboro_yaprobo != null ?
                new ObjectParameter("quien_elaboro_yaprobo", quien_elaboro_yaprobo) :
                new ObjectParameter("quien_elaboro_yaprobo", typeof(string));
    
            var fecha_control_calidad_juridicoParameter = fecha_control_calidad_juridico.HasValue ?
                new ObjectParameter("fecha_control_calidad_juridico", fecha_control_calidad_juridico) :
                new ObjectParameter("fecha_control_calidad_juridico", typeof(System.DateTime));
    
            var control_calidad_juridicoParameter = control_calidad_juridico != null ?
                new ObjectParameter("control_calidad_juridico", control_calidad_juridico) :
                new ObjectParameter("control_calidad_juridico", typeof(string));
    
            var aprobacion_interventoriaParameter = aprobacion_interventoria != null ?
                new ObjectParameter("aprobacion_interventoria", aprobacion_interventoria) :
                new ObjectParameter("aprobacion_interventoria", typeof(string));
    
            var fecha_aprobacionParameter = fecha_aprobacion.HasValue ?
                new ObjectParameter("fecha_aprobacion", fecha_aprobacion) :
                new ObjectParameter("fecha_aprobacion", typeof(System.DateTime));
    
            var linderos_escrituraParameter = linderos_escritura != null ?
                new ObjectParameter("linderos_escritura", linderos_escritura) :
                new ObjectParameter("linderos_escritura", typeof(string));
    
            var linderos_folioParameter = linderos_folio != null ?
                new ObjectParameter("linderos_folio", linderos_folio) :
                new ObjectParameter("linderos_folio", typeof(string));
    
            var linderos_campoParameter = linderos_campo != null ?
                new ObjectParameter("linderos_campo", linderos_campo) :
                new ObjectParameter("linderos_campo", typeof(string));
    
            var analisis_de_hecho_y_derechoParameter = analisis_de_hecho_y_derecho != null ?
                new ObjectParameter("analisis_de_hecho_y_derecho", analisis_de_hecho_y_derecho) :
                new ObjectParameter("analisis_de_hecho_y_derecho", typeof(string));
    
            var inscripcion_catastroParameter = inscripcion_catastro.HasValue ?
                new ObjectParameter("inscripcion_catastro", inscripcion_catastro) :
                new ObjectParameter("inscripcion_catastro", typeof(bool));
    
            var antecedentes_registralesParameter = antecedentes_registrales.HasValue ?
                new ObjectParameter("antecedentes_registrales", antecedentes_registrales) :
                new ObjectParameter("antecedentes_registrales", typeof(bool));
    
            var concepto_juridicoParameter = concepto_juridico != null ?
                new ObjectParameter("concepto_juridico", concepto_juridico) :
                new ObjectParameter("concepto_juridico", typeof(string));
    
            var recomendacionesParameter = recomendaciones != null ?
                new ObjectParameter("recomendaciones", recomendaciones) :
                new ObjectParameter("recomendaciones", typeof(string));
    
            var documentos_analizadosParameter = documentos_analizados != null ?
                new ObjectParameter("documentos_analizados", documentos_analizados) :
                new ObjectParameter("documentos_analizados", typeof(string));
    
            var lindero_norteParameter = lindero_norte != null ?
                new ObjectParameter("lindero_norte", lindero_norte) :
                new ObjectParameter("lindero_norte", typeof(string));
    
            var lindero_occidenteParameter = lindero_occidente != null ?
                new ObjectParameter("lindero_occidente", lindero_occidente) :
                new ObjectParameter("lindero_occidente", typeof(string));
    
            var lindero_orienteParameter = lindero_oriente != null ?
                new ObjectParameter("lindero_oriente", lindero_oriente) :
                new ObjectParameter("lindero_oriente", typeof(string));
    
            var lindero_surParameter = lindero_sur != null ?
                new ObjectParameter("lindero_sur", lindero_sur) :
                new ObjectParameter("lindero_sur", typeof(string));
    
            var pk_predio_folio_matrizParameter = pk_predio_folio_matriz != null ?
                new ObjectParameter("pk_predio_folio_matriz", pk_predio_folio_matriz) :
                new ObjectParameter("pk_predio_folio_matriz", typeof(string));
    
            var direccion_ovcParameter = direccion_ovc != null ?
                new ObjectParameter("direccion_ovc", direccion_ovc) :
                new ObjectParameter("direccion_ovc", typeof(string));
    
            var enla_escritura_se_relaciona_plano_protocolizadoParameter = enla_escritura_se_relaciona_plano_protocolizado.HasValue ?
                new ObjectParameter("enla_escritura_se_relaciona_plano_protocolizado", enla_escritura_se_relaciona_plano_protocolizado) :
                new ObjectParameter("enla_escritura_se_relaciona_plano_protocolizado", typeof(bool));
    
            var complementacionParameter = complementacion != null ?
                new ObjectParameter("complementacion", complementacion) :
                new ObjectParameter("complementacion", typeof(string));
    
            var observaciones_con_respeto_al_propietarioParameter = observaciones_con_respeto_al_propietario != null ?
                new ObjectParameter("observaciones_con_respeto_al_propietario", observaciones_con_respeto_al_propietario) :
                new ObjectParameter("observaciones_con_respeto_al_propietario", typeof(string));
    
            var se_diligencio_ficha_predialParameter = se_diligencio_ficha_predial.HasValue ?
                new ObjectParameter("se_diligencio_ficha_predial", se_diligencio_ficha_predial) :
                new ObjectParameter("se_diligencio_ficha_predial", typeof(bool));
    
            var la_visita_de_campo_produjo_informeParameter = la_visita_de_campo_produjo_informe.HasValue ?
                new ObjectParameter("la_visita_de_campo_produjo_informe", la_visita_de_campo_produjo_informe) :
                new ObjectParameter("la_visita_de_campo_produjo_informe", typeof(bool));
    
            var se_levanto_acta_de_colindaciaParameter = se_levanto_acta_de_colindacia.HasValue ?
                new ObjectParameter("se_levanto_acta_de_colindacia", se_levanto_acta_de_colindacia) :
                new ObjectParameter("se_levanto_acta_de_colindacia", typeof(bool));
    
            var situacion_juridica_inmuebleParameter = situacion_juridica_inmueble != null ?
                new ObjectParameter("situacion_juridica_inmueble", situacion_juridica_inmueble) :
                new ObjectParameter("situacion_juridica_inmueble", typeof(string));
    
            var numero_carpetaParameter = numero_carpeta != null ?
                new ObjectParameter("numero_carpeta", numero_carpeta) :
                new ObjectParameter("numero_carpeta", typeof(string));
    
            var tarjeta_profesional_juridicoParameter = tarjeta_profesional_juridico != null ?
                new ObjectParameter("tarjeta_profesional_juridico", tarjeta_profesional_juridico) :
                new ObjectParameter("tarjeta_profesional_juridico", typeof(string));
    
            var coordinador_juridicoParameter = coordinador_juridico != null ?
                new ObjectParameter("coordinador_juridico", coordinador_juridico) :
                new ObjectParameter("coordinador_juridico", typeof(string));
    
            var nombre_interventorParameter = nombre_interventor != null ?
                new ObjectParameter("nombre_interventor", nombre_interventor) :
                new ObjectParameter("nombre_interventor", typeof(string));
    
            var codigo_municipioParameter = codigo_municipio != null ?
                new ObjectParameter("codigo_municipio", codigo_municipio) :
                new ObjectParameter("codigo_municipio", typeof(string));
    
            var descripcion_municipioParameter = descripcion_municipio != null ?
                new ObjectParameter("descripcion_municipio", descripcion_municipio) :
                new ObjectParameter("descripcion_municipio", typeof(string));
    
            var datos_informe_juridicoParameter = datos_informe_juridico != null ?
                new ObjectParameter("datos_informe_juridico", datos_informe_juridico) :
                new ObjectParameter("datos_informe_juridico", typeof(string));
    
            var datos_informe_campoParameter = datos_informe_campo != null ?
                new ObjectParameter("datos_informe_campo", datos_informe_campo) :
                new ObjectParameter("datos_informe_campo", typeof(string));
    
            var descripicion_destinoParameter = descripicion_destino != null ?
                new ObjectParameter("descripicion_destino", descripicion_destino) :
                new ObjectParameter("descripicion_destino", typeof(string));
    
            var descripicion_sectorParameter = descripicion_sector != null ?
                new ObjectParameter("descripicion_sector", descripicion_sector) :
                new ObjectParameter("descripicion_sector", typeof(string));
    
            var descripicion_adquisicionParameter = descripicion_adquisicion != null ?
                new ObjectParameter("descripicion_adquisicion", descripicion_adquisicion) :
                new ObjectParameter("descripicion_adquisicion", typeof(string));
    
            var numero_ficha_ovcParameter = numero_ficha_ovc != null ?
                new ObjectParameter("numero_ficha_ovc", numero_ficha_ovc) :
                new ObjectParameter("numero_ficha_ovc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFichaPredialesmodificar", id_fichaParameter, folio_matrizParameter, estado_folio_matrizParameter, fecha_apertura_folioParameter, fecha_primera_anotacionParameter, area_escrituraParameter, area_ovcParameter, area_folioParameter, ruta_archivoParameter, razon_diferencia_areasParameter, antecedentesParameter, estudio_folio_matrizParameter, analisis_areasParameter, anotacion_que_afecta_la_inscripcionParameter, proteccion_colectivaParameter, linderosParameter, instrucciones_visita_campoParameter, direccion_folioParameter, quien_elaboro_yaproboParameter, fecha_control_calidad_juridicoParameter, control_calidad_juridicoParameter, aprobacion_interventoriaParameter, fecha_aprobacionParameter, linderos_escrituraParameter, linderos_folioParameter, linderos_campoParameter, analisis_de_hecho_y_derechoParameter, inscripcion_catastroParameter, antecedentes_registralesParameter, concepto_juridicoParameter, recomendacionesParameter, documentos_analizadosParameter, lindero_norteParameter, lindero_occidenteParameter, lindero_orienteParameter, lindero_surParameter, pk_predio_folio_matrizParameter, direccion_ovcParameter, enla_escritura_se_relaciona_plano_protocolizadoParameter, complementacionParameter, observaciones_con_respeto_al_propietarioParameter, se_diligencio_ficha_predialParameter, la_visita_de_campo_produjo_informeParameter, se_levanto_acta_de_colindaciaParameter, situacion_juridica_inmuebleParameter, numero_carpetaParameter, tarjeta_profesional_juridicoParameter, coordinador_juridicoParameter, nombre_interventorParameter, codigo_municipioParameter, descripcion_municipioParameter, datos_informe_juridicoParameter, datos_informe_campoParameter, descripicion_destinoParameter, descripicion_sectorParameter, descripicion_adquisicionParameter, numero_ficha_ovcParameter);
        }
    }
}
